# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Default


steps:
- script: |
    ls -lah 
    echo Begin Push to Tanzu Application Service.
    pwd
  displayName: 'Begin Deployment'
  
- task: CloudFoundryCLIInstall@0
  inputs:
    cfVersion: '6.43.0'


#- task: CloudFoundry@1
#  inputs:
#    cfEndpoint: 'TAS Foundation 001 - Azure'
#    org: 'Enterprise-NonProd'
#    space: 'SANDBOX'
#    deploymentOptions: 'manifest'
#    cfManifest: 'TBS-Demo-Framework-API/manifest.yaml'
#    createServices: false
#    bindServices: false
#    workingDirectory: 'TBS-Demo-Framework-API'

#- task: CloudFoundryCLIInstall@0
#  inputs:
#    cfVersion: '7.4.0'

- task: CloudFoundry@1
  inputs:
    cfEndpoint: 'TAS Foundation 001 - Azure'
    org: 'Enterprise-NonProd'
    space: 'SANDBOX'
    deploymentOptions: 'manual'
    name: 'testapp'
    instances: '3'
#    domain: 'framework-api-sandbox'
    useRoute: true
    buildPackOptions: 'builtin'
    createServices: false
    bindServices: false
    workingDirectory: 'TBS-Demo-Framework-API'